name: Tox

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tox:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.13"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt
    - name: Run Custom Checks
      run: |
        pip install -e .
        PYTHONPATH=$GITHUB_WORKSPACE/tests rkojob run \
        --job custom_checks.job \
        --value src_path=$GITHUB_WORKSPACE/src \
        --value tests_path=$GITHUB_WORKSPACE/tests \
        >> $GITHUB_STEP_SUMMARY
    - name: Run Lint
      run: tox -e lint
    - name: Run Type Checks
      run: tox -e type
    - name: Run Tests
      run: tox -e py${{ matrix.python-version }}
